name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
      - actions/*

  # 如果是 pullrequest 也需要执行编译代码的操作
  pull_request:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-publish-server:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: softethervpn-server
      VPN_NAME: vpnserver
      VPN_BIN_DIR: /usr/local/libexec/softether/vpnserver
      VPN_CMD: vpnserver

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            VPN_NAME=${{ env.VPN_NAME }}
            VPN_BIN_DIR=${{ env.VPN_BIN_DIR }}
            VPN_CMD=${{ env.VPN_CMD }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  build-and-publish-bridge-arm64:
    runs-on: ubuntu-latest
    env:
      BASE_IMANGE_NAME: arm64v8/centos
      BASE_IMAGE_TAG: 7.9.2009
      IMAGE_NAME: softethervpn-bridge-arm64
      VPN_NAME: vpnbridge
      VPN_BIN_DIR: /usr/local/libexec/softether/vpnbridge
      VPN_CMD: vpnbridge
      VPN_CONFIG_OPTIONS: -DSKIP_CPU_FEATURES=1
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: true
          build-args: |
            VPN_NAME=${{ env.VPN_NAME }}
            VPN_BIN_DIR=${{ env.VPN_BIN_DIR }}
            VPN_CMD=${{ env.VPN_CMD }}
            VPN_CONFIG_OPTIONS=${{ env.VPN_CONFIG_OPTIONS }}
            IMAGE_NAME=${{ env.BASE_IMANGE_NAME }}
            IMANGE_VERSION=${{ env.BASE_IMAGE_TAG }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  build-and-publish-bridge:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: softethervpn-bridge
      VPN_NAME: vpnbridge
      VPN_BIN_DIR: /usr/local/libexec/softether/vpnbridge
      VPN_CMD: vpnbridge
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            VPN_NAME=${{ env.VPN_NAME }}
            VPN_BIN_DIR=${{ env.VPN_BIN_DIR }}
            VPN_CMD=${{ env.VPN_CMD }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  build-and-publish-client:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: softethervpn-client
      VPN_NAME: vpnclient
      VPN_BIN_DIR: /usr/local/libexec/softether/vpnclient
      VPN_CMD: vpnclient
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            VPN_NAME=${{ env.VPN_NAME }}
            VPN_BIN_DIR=${{ env.VPN_BIN_DIR }}
            VPN_CMD=${{ env.VPN_CMD }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
